eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 2
#                redis-rate-limiter.requestedTokens: 2
management:
  tracing:
    sampling:
      probability: 1.0